project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "playground/*.qmd"
    - "materials/*.qmd"
  resources:
    - materials/files/**
    - logo.png
    - graphics/**

website:
  title: "CMPSC101 Fall 2026 :: DataStructures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - href: utils/interactivePython.qmd
        text: Interactive
      - href: playground/00_playground.qmd
        text: Playground
      - href: materials/0_materials.qmd
        text: Materials
      - href: https://dodatastructures.com/live
        text: JupyterLite
        target: _blank

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



